### ISSUE TITLE
Table[1] as URL

### ISSUE THREAD

**Issue by FRex** [JakobGreen/lua-requests#14]
A small API addition, perhaps instead of doing

```response = requests.post{url = 'http://httpbin.org/post', data='random data'} ```

it could be possible to do (using [1] as the URL if the only argument is a table).

```response = requests.post{'http://httpbin.org/post', data='random data'}```

thus making the request much closer to actual Python library syntax (with just {} instead of ()) instead of requiring

``` response = requests.post('http://httpbin.org/post', {data='random data'})```

I think it'd just be a one line addition: adding `request.url = request[1] or request.url` to requests.request function.

**Comment by JakobGreen** [comment]
Done in #15
