### ISSUE TITLE
Cannot set headers Content-type?

### ISSUE THREAD

**Issue by kudo28** [JakobGreen/lua-requests#17]
Hi there, I'm using lua-request to post json and I set
```lua
headers = {Content-type= "application/json"}
```
But it didn't work. Here is the log :
```
stdin:1: '}' expected near '='
```
How to solve it?

**Comment by JakobGreen** [comment]
Sorry my example has bad syntax.

Correct syntax:
`headers = {["Content-Type"] = "application/json"}`

**Comment by kudo28** [comment]
thanks!
