### ISSUE TITLE
Replace lbase64 with LuaSockets mime.b64?

### ISSUE THREAD

**Issue by imolein** [JakobGreen/lua-requests#22]
Is there a specific reason why lbase64 is used? 

Why not use the [b64() function of LuaSockets mime module](http://w3.impa.br/~diego/software/luasocket/mime.html#b64) and get rid of this dependency? As far as I tested it on my system, there no difference in performance or something like this. And LuaSocket is not unmaintained like lbase64.

**Comment by JakobGreen** [comment]
Good catch! I just fixed this and updated the rock you submitted in #23

**Comment by imolein** [comment]
Niceeeee. I wanted to do that tomorrow because I'm too tired. So thank you :)
