### ISSUE TITLE
Cant install lua-requests because xml dependency wont install in lua 5.4

### ISSUE THREAD

**Issue by amirhossein-ka** [JakobGreen/lua-requests#32]
i cant install lua-requests because xml cant install in lua5.4
running `sudo luarocks install lua-requests` gives the following error:

```
Installing https://luarocks.org/lua-requests-1.2-2.src.rock
Missing dependencies for lua-requests 1.2-2:
   xml (not installed)
   luasec >= 0.5.1, < 0.8-1 (not installed)

lua-requests 1.2-2 depends on lua >= 5.1 (5.4-1 provided by VM)
lua-requests 1.2-2 depends on luasocket (3.0rc1-2 installed)
lua-requests 1.2-2 depends on md5 (1.3-1 installed)
lua-requests 1.2-2 depends on lua-cjson (2.1.0.6-1 installed)
lua-requests 1.2-2 depends on xml (not installed)

Error: Could not satisfy dependency xml: No results matching query were found for Lua 5.4.
```
OS : Arch linux

**Comment by BugAlpha** [comment]
Same prob here :(

**Comment by Lanttcat** [comment]
I also have same problem on Mac OS, Any update?.

**Comment by lurenyang418** [comment]
@BugAlpha  @Lanttcat @amirhossein-ka  Hi, if you do not need handle with xml , just copy the src/requests.lua with your code. and then comment out https://github.com/JakobGreen/lua-requests/blob/master/src/requests.lua#L8 and https://github.com/JakobGreen/lua-requests/blob/master/src/requests.lua#L114. of course, you need install the dependency manually. 
FYI. Lua 5.4.4
luarocks install luasocket 
luarocks install luasec
luarocks install lua-cjson
luarocks install md5
