### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by rfajfar** [JakobGreen/lua-requests#4]
The module does not support **HTTPS** am I right? Tried to do a **Firebase** wrapper but it does not let me.

**Comment by JakobGreen** [comment]
That is correct. It does not support **HTTPS**. Right now it just wraps up [LuaSocket](http://w3.impa.br/~diego/software/luasocket/). I was planning on removing the **LuaSocket** depency and using something like **cURL** instead which would make **HTTPS** possible. I haven't had the time to do so yet though.

**Comment by rfajfar** [comment]
Could be done using https://github.com/brunoos/luasec and its **ssl.https** module too. Playing around with it just now.

The syntax is close to **socket.http**

**Comment by JakobGreen** [comment]
Thanks to @louis77. This is done.
